### ISSUE TITLE
Weird cropping bug

### ISSUE THREAD

**Issue by shadySource** [forward-pass/LabelBoundingBox#1]
https://youtu.be/g5k2NW5Xi9g

* image appears to be *slightly* cropped when it is first loaded

**Comment by stoplime** [comment]
So it's based on your window screen. If you resize your window to be smaller than the initial image displayed, then it will cover up that part of the image. If you maximize the window, it should be fine since it checks your computer window size for the initial resize. I could try to add dynamic resizing to the image whenever you resize the window, but then I'd have to figure out how tkinter does its resize events.
That's too much work, just maximize your window.
